name: Paper
on:
  pull_request:
    paths:
      - 'paper/**'
jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile paper
        uses: openjournals/whedon-action@v1
        with:
          journal: joss
          paper_path: paper/paper.md